# Use postgres/example user/password credentials
version: '3.1'

services:

  app:
    build: .
    ports:
      - "8080:8080"
  db:
    build: ./db/
    container_name: "tmov_db"
    restart: always
    environment:
      POSTGRES_PASSWORD: "changeme"
    volumes:
      - tmov_dbdata:/var/lib/postgresql/data
    ports:
      - "5111:5432"

volumes:
  tmov_dbdata: